#!/usr/bin/env python
#
#  Create a regional (limited-area) mesh for MPAS-Atmosphere.
#
#  A regional MPAS mesh is made in two steps:
#     1. build a GLOBAL, locally-refined mesh (fine over the area of interest,
#        coarse everywhere else) -- reuses jigsaw_util.build_global_mesh
#     2. CUT the area of interest out of that global mesh with the NCAR
#        MPAS-Limited-Area tool (`create_region`) -- via regional_util
#
#  Smart-transition default (uniform regional mesh)
#  ------------------------------------------------
#  Generating meshes is expensive, so the global background is coarse by
#  default (200 km). The high-resolution flat zone is sized to fully contain
#  the area of interest (plus a small buffer), so EVERY cell kept inside the
#  region ends up at the requested spacing, while the (coarser) transition belt
#  falls OUTSIDE the region and is discarded by the cut -- minimising the number
#  of grid points that are generated but not used.
#
#  Buffer / transition zone (optional, --buffer-res)
#  -------------------------------------------------
#  A uniform regional mesh makes the lateral boundary jump straight from the
#  driving-data spacing (GFS 0.25 deg ~ 25 km) to the regional spacing in one
#  step. Pass --buffer-res to instead keep a buffer ring INSIDE the domain over
#  which the spacing coarsens smoothly from -r to the driving resolution, so
#  the LBC-driven flow can adjust gradually. The cut is enlarged automatically
#  so the ring AND the seven MPAS relaxation rings all fit inside the mesh:
#
#      |<-- area of interest -->|<- ramp ->|<---- flat plateau ---->|
#      |          -r            | -r -> ro |          ro            | ...
#                               W          ^cut boundary   ^mesh edge
#
#  Width and abruptness are two views of one knob: give --buffer-width (km) or
#  --buffer-decay (max cell-to-cell size ratio) and the other is derived.
#
#  by Claude (USP MPAS-Research) 2026, building on create_spherical_grid.py
#

import argparse
import os
import sys

import numpy as np

# Make the shared libs importable even when setup_environment.sh was not sourced
# (it normally adds usp-utils/libs/py to PYTHONPATH). You still need MPAS_ROOT,
# which setup_environment.sh also sets.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "..", "libs", "py"))

import cellwidth_util as cwutil
import jigsaw_util as jutil
import regional_util as rutil

# MPAS-Limited-Area keeps a 7-cell relaxation belt OUTSIDE the region boundary.
# To keep that belt at full resolution too, the flat high-res zone must extend
# past the area of interest by ~ this many cells (7 layers + a small margin).
DEFAULT_BUFFER_CELLS = 10


def _write_domain_file(out_dir, out_base, args, spec, clat, clon,
                       core_radius, area_radius):
    """
    Persist the resolved geometry next to the grid.

    With a buffer, --region-radius no longer describes the extent of the mesh:
    only the inner core is at the requested resolution. Anyone picking the mesh
    up later needs to know where the trustworthy part ends, so write it down.
    """
    path = "%s/%s_domain.txt" % (out_dir, out_base)
    with open(path, "w") as f:
        f.write("Regional mesh: %s\n" % out_base)
        f.write("Generated by: %s\n\n" % " ".join(sys.argv))
        f.write("Region centre (lat, lon): %.4f, %.4f\n" % (clat, clon))
        f.write("Shape                   : %s\n" % args.shape)
        if args.shape != "circle":
            f.write("Area of interest max radius: %.1f km\n" % area_radius)
        f.write("\n%s\n" % cwutil.describe(
            spec, core_radius=core_radius if args.shape == "circle" else None))
        f.write("  %-34s %8.1f km\n" % ("background spacing (-l)", args.l))
        f.write("\nOnly the area of interest is at the target %.1f km "
                "spacing.\nThe buffer ring and the relaxation zone are "
                "deliberately coarser,\nreaching %.1f km at the lateral "
                "boundary to match the driving data.\n"
                % (spec.r, spec.r_outer))
        warnings = spec.validate()
        if warnings:
            f.write("\nWarnings:\n")
            for w in warnings:
                f.write("  - %s\n" % w)
    return path


def main(args):

    mpas_root = os.getenv('MPAS_ROOT')
    if not mpas_root:
        print("ERROR: environment variable MPAS_ROOT is not set.")
        print("Source the usp-utils environment first "
              "(see usp-utils/setup_environment.sh).")
        sys.exit(1)

    out_dir = mpas_root + "/grids/" + args.output
    out_base = os.path.basename(args.output)
    global_base = out_dir + "/" + out_base + "_global"
    global_mesh = global_base + ".nc"
    region_spec = out_dir + "/" + out_base + ".pts"
    p = bool(args.plots)

    if not os.path.exists(out_dir):
        os.makedirs(out_dir)
    else:
        print("Base dir already exists: ", out_dir)

    # ------------------------------------------------------------------
    # 1) Work out the geometry of the region and the high-resolution zone
    # ------------------------------------------------------------------
    boundary_points = None
    preset_points = None

    if args.points_file:
        # Rebuild a region from a points file this script wrote earlier, so an
        # existing domain can be regenerated at a new resolution without
        # retyping its geometry.
        loaded = rutil.read_region_spec(args.points_file)
        print("Loaded region geometry from %s (Type: %s)"
              % (args.points_file, loaded["shape"]))

        # In buffer mode the points file holds the CUT boundary, not the area
        # of interest, so feeding one back in would grow the domain every time.
        domain_txt = os.path.splitext(args.points_file)[0] + "_domain.txt"
        if os.path.exists(domain_txt):
            print("WARNING: %s sits next to this points file, so it was "
                  "written WITH a buffer and describes the CUT boundary, not "
                  "the area of interest. Reusing it will grow the domain by "
                  "the buffer offset again. Give the original area of "
                  "interest instead." % os.path.basename(domain_txt))

        args.shape = "polygon" if loaded["shape"] == "custom" else loaded["shape"]
        if args.clat is None:
            args.clat = loaded["clat"]
        if args.clon is None:
            args.clon = loaded["clon"]
        if args.region_radius is None:
            args.region_radius = loaded["region_radius_km"]
        if args.semi_major is None:
            args.semi_major = loaded["semi_major_km"]
        if args.semi_minor is None:
            args.semi_minor = loaded["semi_minor_km"]
        if not args.orientation:
            args.orientation = loaded["orientation_deg"]
        preset_points = loaded["boundary_points"] or None

    if args.shape == "circle":
        if args.region_radius is None or args.clat is None or args.clon is None:
            print("ERROR: --shape circle needs -clat, -clon and "
                  "--region-radius.")
            sys.exit(1)
        clat, clon = args.clat, args.clon
        # radius of the area of interest (what gets kept by the cut)
        area_radius = args.region_radius

    elif args.shape == "ellipse":
        if None in (args.clat, args.clon, args.semi_major, args.semi_minor):
            print("ERROR: --shape ellipse needs -clat, -clon, --semi-major "
                  "and --semi-minor.")
            sys.exit(1)
        clat, clon = args.clat, args.clon
        # the flat high-res zone must cover the longest axis
        area_radius = max(args.semi_major, args.semi_minor)

    elif args.shape == "box":
        if None in (args.lat_min, args.lat_max, args.lon_min, args.lon_max):
            print("ERROR: --shape box needs --lat-min --lat-max "
                  "--lon-min --lon-max.")
            sys.exit(1)
        clat, clon = rutil.box_center(args.lat_min, args.lat_max,
                                      args.lon_min, args.lon_max)
        # circle that contains the whole box -> sizes the high-res flat zone
        area_radius = rutil.box_circumscribed_radius_km(
            args.lat_min, args.lat_max, args.lon_min, args.lon_max)
        boundary_points = rutil.box_boundary_points(
            args.lat_min, args.lat_max, args.lon_min, args.lon_max)

    elif args.shape == "polygon":
        if preset_points is not None:
            boundary_points = preset_points
        elif args.polygon_file:
            boundary_points = rutil.read_polygon_file(args.polygon_file)
        else:
            print("ERROR: --shape polygon needs --polygon-file FILE "
                  "(or --points-file FILE).")
            sys.exit(1)
        # Use a user-given inside point, else a point guaranteed to be inside
        # the polygon (robust for concave shapes, where the vertex mean can
        # fall outside and make create_region fail).
        if args.clat is not None and args.clon is not None:
            clat, clon = args.clat, args.clon
        else:
            clat, clon = rutil.polygon_inside_point(boundary_points)
        area_radius = rutil.max_radius_km(clat, clon, boundary_points)

    else:
        print("Unknown shape:", args.shape)
        sys.exit(1)

    buffer_on = args.buffer_res is not None

    # ------------------------------------------------------------------
    # 2) Resolve the resolution profile
    # ------------------------------------------------------------------
    spec = None
    dist_fn = None
    core_radius = None
    core_points = None
    cut_points = None
    cut_radius = None
    boundaries = None

    if not buffer_on:
        # Classic uniform regional mesh. The flat high-resolution zone must
        # cover the area of interest PLUS the relaxation belt, so every kept
        # cell is at the target spacing and the (discarded) transition belt
        # starts only beyond it.
        if args.buffer is not None:
            margin = args.buffer
        else:
            margin = DEFAULT_BUFFER_CELLS * args.r
        radius_high = area_radius + margin

        print("Region centre (lat, lon): %.3f, %.3f" % (clat, clon))
        print("Area of interest radius : %.1f km" % area_radius)
        print("High-res flat zone radius: %.1f km (area + %.1f km buffer)"
              % (radius_high, margin))
        print("Background (global) spacing: %.1f km" % args.l)
        print("Target spacing inside region: %.1f km" % args.r)

    else:
        # Buffer / transition zone. --buffer keeps its name but changes role:
        # its old job (keeping the relaxation belt at full resolution) is now
        # done by the flat plateau, so here it is an optional extra full
        # resolution margin around the area of interest, defaulting to none.
        core_margin = args.buffer if args.buffer is not None else 0.0

        if args.buffer_width is not None and args.buffer_decay is not None:
            print("ERROR: --buffer-width and --buffer-decay are two ways of "
                  "saying the same thing; give only one.")
            sys.exit(1)
        if args.buffer_res <= args.r:
            print("ERROR: --buffer-res (%.1f km) must be coarser than -r "
                  "(%.1f km)." % (args.buffer_res, args.r))
            sys.exit(1)

        if args.buffer_width is not None:
            width = args.buffer_width
        else:
            decay = args.buffer_decay if args.buffer_decay is not None else 1.10
            width = cwutil.ramp_width_from_growth(args.r, args.buffer_res,
                                                  decay, args.buffer_profile)

        spec = cwutil.BufferSpec(
            r=args.r, r_outer=args.buffer_res, width=width,
            profile=args.buffer_profile, n_pre=args.relax_pre_cells,
            n_post=args.relax_post_cells, l=args.l,
            outer_slope=100.0 / args.tr)

        # Boundary of the area of interest, densified finely enough that
        # distances measured to the sampled polyline are accurate.
        spacing = min(args.r, width) / 4.0
        core_radius = area_radius + core_margin

        # Outline of the area of interest, for every shape. Built even for a
        # circle, because the plots draw the real outlines -- circles at a
        # circumscribed radius would badly misrepresent any other domain.
        core_points = rutil.region_boundary_polygon(
            args.shape, clat, clon,
            region_radius_km=core_radius,
            semi_major_km=args.semi_major, semi_minor_km=args.semi_minor,
            orientation_deg=args.orientation,
            boundary_points=boundary_points, spacing_km=spacing)

        if args.shape == "circle":
            # Exact analytic fast path -- no KDTree, no point-in-polygon.
            dist_fn = rutil.circle_distance_fn(clat, clon, core_radius)
            cut_radius = core_radius + spec.cut_offset
        else:
            if core_margin > 0.0:
                core_points = rutil.offset_polygon_km(core_points, core_margin,
                                                      clat, clon)
            dist_fn = rutil.polygon_distance_fn(core_points, clat, clon,
                                                spacing_km=spacing)
            cut_points = rutil.offset_polygon_km(core_points, spec.cut_offset,
                                                 clat, clon)

        # The buffer follows the region boundary, so the plotted outlines are
        # constant-distance offsets of it, not circles.
        # NB the labels: MPAS-Limited-Area grows its 7 relaxation rings OUTWARD
        # from the points-file boundary, so the cells beyond that line are part
        # of the final mesh, not offcuts. Calling it a "cut boundary" invited
        # exactly the opposite reading.
        boundaries = [
            (core_points, "area of interest", "w"),
            (rutil.offset_polygon_km(core_points, spec.width, clat, clon),
             "end of ramp", "darkorange"),
            (rutil.offset_polygon_km(core_points, spec.cut_offset, clat, clon),
             "LBC zone starts (.pts)", "crimson"),
            (rutil.offset_polygon_km(core_points, spec.mesh_offset, clat, clon),
             "mesh edge", "black"),
        ]

        print("Region centre (lat, lon): %.3f, %.3f" % (clat, clon))
        print("Shape                   : %s" % args.shape)
        print(cwutil.describe(spec, core_radius=core_radius
                              if args.shape == "circle" else None))
        print("  %-34s %8.1f km" % ("background spacing (-l)", args.l))
        if args.shape != "circle":
            print("  %-34s %8.1f km  (circumscribed, shape-following buffer)"
                  % ("area of interest max radius", area_radius))
        for warning in spec.validate():
            print("WARNING: %s" % warning)

    # ------------------------------------------------------------------
    # 3) Build the global, locally-refined mesh
    # ------------------------------------------------------------------
    if args.preview:
        if not buffer_on:
            print("\n[preview] --preview only previews the buffer profile, "
                  "and --buffer-res was not given.")
            print("[preview] Nothing to preview for a uniform regional mesh; "
                  "re-run without --preview to build it.")
            sys.exit(0)
        print("\n[preview] Building the analytic resolution field only "
              "(jigsaw is NOT run).")
        cell_width, plon, plat = jutil.bufferedRegionVsLatLon(
            spec, dist_fn, clon=clon, clat=clat,
            dlat=args.hfun_dlat,
            dtype=(np.float32 if args.hfun_float32 else None))
        preview_png = "%s/%s_preview.png" % (out_dir, out_base)
        preview_png, preview_profile_png = jutil.plot_cellwidth_field(
            cell_width, plon, plat, preview_png,
            clon=clon, clat=clat, spec=spec, core_radius=core_radius,
            boundaries=boundaries,
            title="%s: target cell width (km)" % out_base)
        _write_domain_file(out_dir, out_base, args, spec, clat, clon,
                           core_radius, area_radius)
        print("\n[preview] resolution map   : %s" % preview_png)
        if preview_profile_png:
            print("[preview] resolution profile: %s" % preview_profile_png)
        print("[preview] geometry summary : %s/%s_domain.txt"
              % (out_dir, out_base))
        print("[preview] Re-run without --preview to build the mesh.")
        return

    print("\n[1/3] Building global locally-refined mesh ...")
    jutil.build_global_mesh(
        "localref", global_base, out_dir, global_mesh,
        r=args.r, l=args.l,
        rad=(radius_high if not buffer_on else None), tr=args.tr,
        clon=clon, clat=clat, plots=False,
        buffer_spec=spec, dist_fn=dist_fn,
        hfun_dlat=args.hfun_dlat,
        hfun_dtype=(np.float32 if args.hfun_float32 else None))

    # ------------------------------------------------------------------
    # 4) Write the region spec and cut the regional mesh out
    # ------------------------------------------------------------------
    print("\n[2/3] Writing region specification -> %s" % region_spec)
    if buffer_on:
        # The cut boundary is the area of interest pushed outward far enough
        # that the ramp and the first relaxation rings are inside it.
        if args.shape == "circle":
            rutil.write_region_spec(region_spec, out_base, "circle",
                                    clat=clat, clon=clon,
                                    region_radius_km=cut_radius)
        else:
            rutil.write_region_spec(region_spec, out_base, "custom",
                                    clat=clat, clon=clon,
                                    boundary_points=cut_points)
        _write_domain_file(out_dir, out_base, args, spec, clat, clon,
                           core_radius, area_radius)
    elif args.shape == "circle":
        rutil.write_region_spec(region_spec, out_base, "circle",
                                clat=clat, clon=clon,
                                region_radius_km=area_radius)
    elif args.shape == "ellipse":
        rutil.write_region_spec(region_spec, out_base, "ellipse",
                                clat=clat, clon=clon,
                                semi_major_km=args.semi_major,
                                semi_minor_km=args.semi_minor,
                                orientation_deg=args.orientation)
    else:  # box / polygon -> custom polygon
        rutil.write_region_spec(region_spec, out_base, "custom",
                                clat=clat, clon=clon,
                                boundary_points=boundary_points)

    print("\n[3/3] Cutting regional mesh with MPAS-Limited-Area ...")
    rutil.cut_regional_mesh(global_mesh, region_spec, out_dir)

    regional_mesh = "%s/%s.grid.nc" % (out_dir, out_base)

    # Optional quick-look plot of the resulting regional mesh resolution.
    # By default it goes next to the grid; --plot-out overrides the location.
    plot_png = None
    profile_png = None
    if p or args.plot_out:
        plot_png = jutil.resolve_plot_path(args.plot_out, out_dir, out_base)
        print("\nPlotting resolution -> %s" % plot_png)
        plot_png, profile_png = jutil.plot_resolution(
            regional_mesh, plot_png, states=True,
            center=((clat, clon) if buffer_on else None),
            spec=spec, core_radius=core_radius,
            boundaries=boundaries, dist_fn=dist_fn)

    print("\nDone! Regional mesh written under: " + out_dir)
    print("  global (pre-cut) mesh : %s" % global_mesh)
    print("  region spec           : %s" % region_spec)
    print("  regional mesh         : %s" % regional_mesh)
    print("  partition graph       : %s/%s.graph.info" % (out_dir, out_base))
    if buffer_on:
        print("  domain summary        : %s/%s_domain.txt" % (out_dir, out_base))
    if plot_png:
        print("  resolution map        : %s" % plot_png)
    if profile_png:
        print("  resolution profile    : %s" % profile_png)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawTextHelpFormatter)

    parser.add_argument(
        "-r", "--high", dest="r",
        required=False, default=30, type=float,
        help="Target grid spacing INSIDE the region, in km (default: 30 km)",
        metavar="FLOAT")

    parser.add_argument(
        "-l", "--low", dest="l",
        required=False, default=200, type=float,
        help="Background (global) grid spacing in km. Kept coarse on purpose "
             "since\nit is discarded by the cut (default: 200 km)",
        metavar="FLOAT")

    parser.add_argument(
        "--shape", dest="shape",
        required=False, default="circle", type=str,
        help="Region shape (default: circle):\n"
             "  circle  -> -clat -clon --region-radius\n"
             "  ellipse -> -clat -clon --semi-major --semi-minor "
             "[--orientation]\n"
             "  box     -> --lat-min --lat-max --lon-min --lon-max\n"
             "  polygon -> --polygon-file [-clat -clon as inside point]",
        metavar="STR")

    parser.add_argument(
        "-clat", "--center_latitude", dest="clat",
        required=False, default=None, type=float,
        help="Latitude (deg) of the region centre - circle/ellipse "
             "(or inside point for polygon)",
        metavar="FLOAT")

    parser.add_argument(
        "-clon", "--center_longitude", dest="clon",
        required=False, default=None, type=float,
        help="Longitude (deg) of the region centre - circle/ellipse "
             "(or inside point for polygon)",
        metavar="FLOAT")

    parser.add_argument(
        "--region-radius", dest="region_radius",
        required=False, default=None, type=float,
        help="Radius of the area of interest in km - circle shape",
        metavar="FLOAT")

    parser.add_argument(
        "--semi-major", dest="semi_major",
        required=False, default=None, type=float,
        help="Ellipse semi-major axis in km - ellipse shape",
        metavar="FLOAT")
    parser.add_argument(
        "--semi-minor", dest="semi_minor",
        required=False, default=None, type=float,
        help="Ellipse semi-minor axis in km - ellipse shape",
        metavar="FLOAT")
    parser.add_argument(
        "--orientation", dest="orientation",
        required=False, default=0.0, type=float,
        help="Ellipse orientation in deg, clockwise from north - ellipse "
             "shape (default: 0)",
        metavar="FLOAT")

    parser.add_argument(
        "--points-file", dest="points_file",
        required=False, default=None, type=str,
        help="Rebuild the region from an existing MPAS-Limited-Area points\n"
             "file (a <name>.pts this script wrote earlier), instead of\n"
             "giving --shape and its coordinates. Handles Type: circle,\n"
             "ellipse and custom. Only the GEOMETRY is stored in a .pts, so\n"
             "-r, -l, -tr and the --buffer-* flags still apply as given here.\n"
             "Any -clat/-clon/--region-radius you pass explicitly wins over\n"
             "the file.",
        metavar="PATH")

    parser.add_argument(
        "--polygon-file", dest="polygon_file",
        required=False, default=None, type=str,
        help="Text file with 'lat, lon' boundary points (one per line) - "
             "polygon shape",
        metavar="PATH")

    parser.add_argument(
        "--lat-min", dest="lat_min", required=False, default=None, type=float,
        help="South edge (deg) - box shape", metavar="FLOAT")
    parser.add_argument(
        "--lat-max", dest="lat_max", required=False, default=None, type=float,
        help="North edge (deg) - box shape", metavar="FLOAT")
    parser.add_argument(
        "--lon-min", dest="lon_min", required=False, default=None, type=float,
        help="West edge (deg) - box shape", metavar="FLOAT")
    parser.add_argument(
        "--lon-max", dest="lon_max", required=False, default=None, type=float,
        help="East edge (deg) - box shape", metavar="FLOAT")

    parser.add_argument(
        "--buffer", dest="buffer",
        required=False, default=None, type=float,
        help="Extra full-resolution margin (km) around the area of interest.\n"
             "Without --buffer-res this keeps the MPAS relaxation belt at\n"
             "full resolution and defaults to 10 x -r (the 7-cell relaxation\n"
             "zone plus a margin). With --buffer-res that job is done by the\n"
             "flat plateau instead, so here it just widens the full-resolution\n"
             "core before the ramp starts, and defaults to 0.",
        metavar="FLOAT")

    parser.add_argument(
        "-tr", "--transitionradius", dest="tr",
        required=False, default=600, type=float,
        help="Steepness of the (discarded) outer ramp towards -l, as a\n"
             "reference length in km: the ramp slope is 100/tr km per km, so\n"
             "the belt is actually l*tr/100 km wide, NOT tr km. It lies\n"
             "outside the region and is discarded, so it mainly affects\n"
             "generation cost (default: 600 km)",
        metavar="FLOAT")

    buf = parser.add_argument_group(
        "Buffer / transition zone (optional)",
        "Keep a buffer ring INSIDE the regional domain over which the spacing\n"
        "coarsens smoothly from -r to the lateral-BC driving resolution,\n"
        "instead of a uniform mesh that jumps at the boundary. Off unless\n"
        "--buffer-res is given.")

    buf.add_argument(
        "--buffer-res", "--outer-resolution", dest="buffer_res",
        required=False, default=None, type=float,
        help="Cell spacing (km) at the OUTER edge of the regional domain.\n"
             "Enables the buffer. Set it to your lateral boundary condition\n"
             "resolution: 25 for GFS 0.25 deg, 31 for ERA5. Must be coarser\n"
             "than -r and finer than -l. (default: off -> uniform mesh)",
        metavar="FLOAT")

    buf.add_argument(
        "--buffer-width", dest="buffer_width",
        required=False, default=None, type=float,
        help="Width (km) of the ramp from -r to --buffer-res. Mutually\n"
             "exclusive with --buffer-decay -- each one implies the other.",
        metavar="FLOAT")

    buf.add_argument(
        "--buffer-decay", "--buffer-growth", dest="buffer_decay",
        required=False, default=None, type=float,
        help="Abruptness of the transition, as the maximum size ratio between\n"
             "adjacent cells in the ramp. Larger = more abrupt = narrower\n"
             "ring: W = C x (buffer_res - r) / (decay - 1), where C depends on\n"
             "--buffer-profile. Mesh-quality guidance is 1.05-1.15, and jigsaw\n"
             "applies no gradient limiter, so values above ~1.2 show up as\n"
             "poor cells. (default: 1.10)",
        metavar="FLOAT")

    buf.add_argument(
        "--buffer-profile", dest="buffer_profile",
        required=False, default="tanh", type=str,
        choices=list(cwutil.PROFILES),
        help="Shape of the ramp (default: tanh). All of them hit -r and\n"
             "--buffer-res exactly; they differ in how much width a given\n"
             "--buffer-decay costs (C = 1.0 linear, 1.5 smoothstep, 1.57\n"
             "cosine, 1.875 smootherstep, 2.34 tanh). smoothstep is the\n"
             "cheapest smooth option; linear is narrowest but kinks at the\n"
             "two joins.")

    buf.add_argument(
        "--relax-pre-cells", dest="relax_pre_cells",
        required=False, default=2, type=int,
        help="Cells of the flat --buffer-res belt placed INSIDE the cut\n"
             "boundary, absorbing the one-cell jitter of the region-marking\n"
             "walk (default: 2)",
        metavar="INT")

    buf.add_argument(
        "--relax-post-cells", dest="relax_post_cells",
        required=False, default=3, type=int,
        help="Cells of the flat belt kept beyond the 7th MPAS relaxation ring\n"
             "before the discarded outer ramp starts (default: 3)",
        metavar="INT")

    buf.add_argument(
        "--preview", dest="preview",
        required=False, action="store_true",
        help="Resolve the geometry, print the domain table and save the\n"
             "ANALYTIC cell-width map plus its radial profile, then exit\n"
             "WITHOUT running jigsaw. Takes seconds instead of minutes, so\n"
             "tune --buffer-width / --buffer-decay with this first.")

    buf.add_argument(
        "--hfun-dlat", dest="hfun_dlat",
        required=False, default=None, type=float,
        help="Spacing (deg) of the working grid the resolution field is built\n"
             "on. Default is -r/200, i.e. 7201 x 14401 points at -r 5. The\n"
             "field only has to resolve the TRANSITION, not the cell size, so\n"
             "a coarser grid is usually fine and much cheaper. Advanced use.",
        metavar="FLOAT")

    buf.add_argument(
        "--hfun-float32", dest="hfun_float32",
        required=False, action="store_true",
        help="Store the resolution field in single precision: halves memory\n"
             "and shrinks the intermediate jigsaw HFUN file. Advanced use.")

    parser.add_argument(
        "-o", "--output", dest="output",
        required=False, default="regional_grid", type=str,
        help="Output basename for directory and files.",
        metavar="STR")

    parser.add_argument(
        "-p", "--plot", dest="plots",
        required=False, action="store_true",
        help="If given, save a quick-look PNG of the regional mesh resolution.\n"
             "By default it is written next to the grid, as\n"
             "$MPAS_ROOT/grids/<output>/<output>_resolution.png.\n"
             "No plot unless this flag is present.")

    parser.add_argument(
        "--plot-out", dest="plot_out",
        required=False, default=None, type=str,
        help="Custom path for the resolution plot (a file, or a directory in\n"
             "which <output>_resolution.png is written). Implies --plot.\n"
             "Omit to use the default location next to the grid.",
        metavar="PATH")

    if len(sys.argv) < 2:
        parser.print_help()
        sys.exit(1)

    args = parser.parse_args()

    main(args)
